# Default values for opendistro-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: elasticsearch
  clusterName: elasticsearch
  namespace: elasticsearch
  roleName: es-master
  role: master

roles:
  master: true
  ingest: false
  data: false

containers:
  image: amazon/opendistro-for-elasticsearch
  imageTag: 0.9.0
  pullPolicy: Always

annotations:
  external_dns: elk.sec.example.com
  iam_arn: <ARN_OF_IAM_ROLE_FOR_CONTAINER>

discovery:
  name: elasticsearch-discovery
  role: master
  clusterIP: None

security:
  ports:
    httpPort: 9200
    transportPort: 9300
    metricsPort: 9600
  deployments:
    privileged: true

resources:
  replicas: 3
  esJavaOpts: "-Xms6g -Xmx6g"
  max_map_count: 262144
  requests:
    memory: 12Gi
    cpu: 2
  limits:
    memory: 12Gi
    cpu: 2

environmentalVariables:
  CLUSTER_NAME: "testing"
  NUMBER_OF_MASTERS: "3"
  NETWORK_HOST: "0.0.0.0"
  TRANSPORT_TLS_PEM_PASS: "REPLACE_WITH_TLS_PRIVATE_KEY_PASSPHRASE" # Replace this with the passphrase for the TLS private key
  HTTP_TLS_PEM_PASS: "REPLACE_WITH_TLS_PRIVATE_KEY_PASSPHRASE" # Replace this with the passphrase for the TLS private key
